// mem test harness.
//
// Everything here runs with no network and no API key. Two seams make that
// possible, and neither is test-only code inside the product:
//
//   1. local.js resolves Chrome's built-in model lazily, by reading
//      globalThis.LanguageModel at call time. So defining a stub before the
//      first call is enough to exercise the whole on-device path.
//   2. Setting the provider to 'local' routes embeddings through the real
//      hashed embedder, which is pure, deterministic JavaScript. Every
//      similarity number below is reproducible.
//
// Served from localhost this page has its own origin, so its IndexedDB is a
// different database from the installed extension's. Running it cannot touch
// real memories.

// ---------- stub the on-device model (before any module reads it) ----------

globalThis.LanguageModel = {
  async availability() { return 'available'; },
  async create() {
    return {
      async prompt(text) {
        // The summarizer path is the only thing that asks for JSON.
        if (/JSON|summary/i.test(text)) {
          return JSON.stringify({
            summary: 'A stubbed summary produced by the test harness for deterministic runs.',
            tags: ['testing', 'harness', 'retrieval'],
            keyFacts: ['Generated by the harness, not a model.'],
            contentType: 'article',
            entities: [],
          });
        }
        return 'stub answer';
      },
      async *promptStreaming() { yield 'stub answer'; },
      destroy() {},
    };
  },
};

import * as vec from '../lib/vec.js';
import * as text from '../lib/text.js';
import * as local from '../lib/local.js';
import * as store from '../lib/storage.js';
import * as index from '../lib/index.js';
import * as ai from '../lib/ai.js';
import * as search from '../lib/search.js';
import * as ingestMod from '../lib/ingest.js';
import * as entities from '../lib/entities.js';
import * as episodes from '../lib/episodes.js';
import * as openloops from '../lib/openloops.js';
import * as resurface from '../lib/resurface.js';
import { isFollowUp } from '../lib/conversation.js';
import * as commitments from '../lib/commitments.js';

// ---------- tiny test framework ----------

const suites = [];
let current = null;

function describe(name, fn) {
  current = { name, cases: [] };
  suites.push(current);
  fn();
  current = null;
}
function it(name, fn) { current.cases.push({ name, fn }); }

class Skip extends Error {}
function skip(why) { throw new Skip(why); }

function assert(cond, msg) {
  if (!cond) throw new Error(msg || 'assertion failed');
}
function eq(a, b, msg) {
  if (a !== b) throw new Error(`${msg || 'expected equal'}\n  actual:   ${fmt(a)}\n  expected: ${fmt(b)}`);
}
function close(a, b, tol, msg) {
  if (Math.abs(a - b) > tol) throw new Error(`${msg || 'expected close'}\n  actual:   ${a}\n  expected: ${b} ±${tol}`);
}
function gt(a, b, msg) {
  if (!(a > b)) throw new Error(`${msg || 'expected greater'}\n  ${fmt(a)} is not > ${fmt(b)}`);
}
function fmt(v) {
  if (typeof v === 'number') return Number.isInteger(v) ? String(v) : v.toFixed(6);
  if (typeof v === 'string') return JSON.stringify(v.length > 120 ? v.slice(0, 120) + '…' : v);
  return String(v);
}

// ---------- fixtures ----------

const LOCAL_SPACE = local.LOCAL_SPACE;

/** Reset both the database and the in-memory index between suites. */
async function freshDb() {
  await store.ready();
  await store.clear();
  index._reset();
  await store.metaSet('index', null);
  ai.clearEmbedCache();
  search.invalidateAnswerCache();
}

async function useLocalProvider() {
  await ai.switchProvider('local');
}

/**
 * Seed a document the way ingest does, but without the summarizer — used by
 * tests that care about retrieval rather than about ingest itself.
 */
async function seed({ id, title, body, summary, createdAt = Date.now(), sourceKind = 'web', tags = [], extra = null, chunked = true }) {
  const chunks = chunked && body.length > 1600
    ? text.chunkText(body)
    : [{ text: body, start: 0, i: 0 }];

  const docText = [title, summary || '', tags.join(', '), body.slice(0, 2000)].filter(Boolean).join('\n\n');
  const docVec = local.embed(docText);
  const chunkRecords = chunks.map((c) => ({
    text: c.text,
    start: c.start,
    vec: local.embed(`${title}\n\n${c.text}`),
  }));

  const memory = {
    id, url: `https://example.test/${id}`, title,
    summary: summary || title, text: body, tags, keyFacts: [],
    contentType: 'article', sourceKind, sourceLabel: '', siteName: 'example.test',
    createdAt, updatedAt: createdAt, embedSpace: LOCAL_SPACE,
    chunkCount: chunkRecords.length, excerpt: '', selection: '',
    favicon: '', author: '', publishedAt: '', mime: '', extra,
    ...(summary ? {} : { lightweight: true }),
  };
  await store.put(memory);
  await index.addDoc({
    id, vec: docVec, space: LOCAL_SPACE, createdAt,
    chunks: chunkRecords,
    tokensText: [title, summary || '', tags.join(' '), body].filter(Boolean).join('\n'),
  });
  return memory;
}

/** Filler prose with none of the marker vocabulary, to pad long documents. */
function filler(paragraphs, seedWord = 'general') {
  const sentences = [
    `The ${seedWord} overview begins with background material that sets out the ordinary situation.`,
    `Standard procedure covers the usual arrangements without departing from established practice.`,
    `Routine observations were collected and tabulated in the customary manner throughout.`,
    `Nothing in this passage departs from the conventional treatment of the ordinary subject.`,
    `Further discussion continues along familiar lines with additional supporting commentary.`,
  ];
  const out = [];
  for (let i = 0; i < paragraphs; i++) {
    out.push(sentences.map((s) => s.replace('§', String(i))).join(' '));
  }
  return out.join('\n\n');
}

// ================= vector maths =================

describe('Vector maths', () => {
  it('normalize produces a unit vector', () => {
    const v = vec.normalize([3, 4, 0, 0]);
    close(Math.sqrt(v.reduce((s, x) => s + x * x, 0)), 1, 1e-6, 'length should be 1');
    close(v[0], 0.6, 1e-6);
    close(v[1], 0.8, 1e-6);
  });

  it('normalize leaves a zero vector alone instead of dividing by zero', () => {
    const v = vec.normalize([0, 0, 0]);
    assert(v.every((x) => x === 0), 'should stay zero');
    assert(!v.some(Number.isNaN), 'must not produce NaN');
  });

  it('dot of a unit vector with itself is 1', () => {
    const v = vec.normalize([0.2, -0.7, 0.4, 0.1, 0.9]);
    close(vec.dot(v, v), 1, 1e-6);
  });

  it('quantisation round-trips within half a step', () => {
    const v = vec.normalize(Array.from({ length: 256 }, (_, i) => Math.sin(i * 0.37)));
    const { q, scale } = vec.quantize(v);
    const back = vec.dequantize(q, scale);
    let maxErr = 0;
    for (let i = 0; i < v.length; i++) maxErr = Math.max(maxErr, Math.abs(v[i] - back[i]));
    // The step size is the per-vector scale, so half of it is the worst case.
    assert(maxErr <= scale * 0.5 + 1e-9, `max component error ${maxErr} exceeds half a step (${scale * 0.5})`);
    return `step ${scale.toExponential(3)}, worst component error ${maxErr.toExponential(3)}`;
  });

  it('quantising a zero vector yields a zero scale rather than NaN', () => {
    const { q, scale } = vec.quantize(new Float32Array(16));
    eq(scale, 0);
    assert(q.every((x) => x === 0));
    const back = vec.dequantize(q, scale);
    assert(back.every((x) => x === 0), 'dequantising must not produce NaN');
  });

  it('quantised similarity tracks exact similarity at full 1536 width', () => {
    // At mem's real width the components of a unit vector are tiny, which is
    // exactly where a fixed quantisation scale falls apart. This asserts the
    // per-vector scale is doing its job.
    const a = vec.normalize(Array.from({ length: 1536 }, (_, i) => Math.sin(i * 0.11)));
    const b = vec.normalize(Array.from({ length: 1536 }, (_, i) => Math.sin(i * 0.11 + 0.3)));
    const exact = vec.dot(a, b);
    const qa = vec.quantize(a);
    const qb = vec.quantize(b);
    const approx = vec.dot(vec.dequantize(qa.q, qa.scale), vec.dequantize(qb.q, qb.scale));
    close(approx, exact, 0.005, 'quantised similarity should stay within 0.005 of exact');
    return `exact ${exact.toFixed(6)} vs quantised ${approx.toFixed(6)} (error ${Math.abs(approx - exact).toFixed(6)})`;
  });

  it('the per-vector scale beats a fixed scale at high dimension', () => {
    const a = vec.normalize(Array.from({ length: 1536 }, (_, i) => Math.sin(i * 0.11)));
    const b = vec.normalize(Array.from({ length: 1536 }, (_, i) => Math.sin(i * 0.11 + 0.3)));
    const exact = vec.dot(a, b);

    const qa = vec.quantize(a);
    const qb = vec.quantize(b);
    const perVector = Math.abs(vec.dot(vec.dequantize(qa.q, qa.scale), vec.dequantize(qb.q, qb.scale)) - exact);

    // Reproduce the old fixed-scale behaviour for comparison.
    const fixed = (v) => {
      const out = new Float32Array(v.length);
      for (let i = 0; i < v.length; i++) {
        out[i] = Math.max(-127, Math.min(127, Math.round(v[i] * 127))) / 127;
      }
      return out;
    };
    const fixedErr = Math.abs(vec.dot(fixed(a), fixed(b)) - exact);
    gt(fixedErr, perVector, 'the per-vector scale should be more accurate');
    return `error: per-vector ${perVector.toFixed(6)}, fixed scale ${fixedErr.toFixed(6)} (${(fixedErr / Math.max(perVector, 1e-9)).toFixed(0)}× worse)`;
  });

  it('scanPacked agrees with a direct dot product', () => {
    const dim = 64;
    const rows = 10;
    const matrix = new Int8Array(rows * dim);
    const scales = new Float32Array(rows);
    const vecs = [];
    for (let r = 0; r < rows; r++) {
      const v = vec.normalize(Array.from({ length: dim }, (_, i) => Math.sin(i * (r + 1) * 0.13)));
      vecs.push(v);
      const { q, scale } = vec.quantize(v);
      matrix.set(q, r * dim);
      scales[r] = scale;
    }
    const qv = vec.quantize(vecs[3]);
    const scores = vec.scanPacked(qv.q, qv.scale, matrix, scales, dim, rows);
    let best = 0;
    for (let r = 1; r < rows; r++) if (scores[r] > scores[best]) best = r;
    eq(best, 3, 'the query vector should match its own row');
    close(scores[3], 1, 0.01, 'self-similarity should be ~1');
    // Every row should track its exact counterpart.
    for (let r = 0; r < rows; r++) {
      close(scores[r], vec.dot(vecs[3], vecs[r]), 0.01, `row ${r} should match the exact dot product`);
    }
  });

  it('topK returns the k highest scores in order', () => {
    const scores = Float32Array.from([0.1, 0.9, 0.5, 0.7, 0.2, 0.95, 0.3]);
    const top = vec.topK(scores, 3);
    eq(top.length, 3);
    eq(top[0].i, 5);
    eq(top[1].i, 1);
    eq(top[2].i, 3);
  });

  it('topK honours the allow filter', () => {
    const scores = Float32Array.from([0.9, 0.8, 0.7, 0.6]);
    const top = vec.topK(scores, 2, (i) => i !== 0);
    eq(top[0].i, 1);
    eq(top[1].i, 2);
  });

  it('RRF rewards appearing in both lists over topping just one', () => {
    // This is the property that matters for hybrid retrieval: a document
    // both arms agree on beats one that only a single arm ranked first.
    const fused = vec.rrf([
      { name: 'vector', ids: ['a', 'b'] },
      { name: 'lexical', ids: ['b', 'c'] },
    ]);
    eq(fused[0].id, 'b', 'the document both arms found should win');
    assert(fused[0].ranks.vector === 2 && fused[0].ranks.lexical === 1,
      'the winner should carry its rank in each list');
  });

  it('RRF needs no score normalisation to combine unlike scales', () => {
    // BM25 scores are unbounded and cosine scores sit in [-1, 1]. RRF only
    // reads rank position, so the scales never have to be reconciled.
    const fused = vec.rrf([
      { name: 'lexical', ids: ['big', 'small'] },   // scores might be 40.2, 38.9
      { name: 'vector', ids: ['small', 'big'] },    // scores might be 0.81, 0.79
    ]);
    eq(fused.length, 2);
    close(fused[0].score, fused[1].score, 1e-3, 'a symmetric disagreement should be near-tied');
  });

  it('RRF weights shift the outcome', () => {
    const even = vec.rrf([
      { name: 'x', ids: ['a', 'z'], weight: 1 },
      { name: 'y', ids: ['z', 'a'], weight: 1 },
    ]);
    eq(even[0].id, 'a', 'ties break toward the first list');
    const weighted = vec.rrf([
      { name: 'x', ids: ['a', 'z'], weight: 0.2 },
      { name: 'y', ids: ['z', 'a'], weight: 1 },
    ]);
    eq(weighted[0].id, 'z', 'the heavier list should decide');
  });

  it('MMR drops near-duplicates in favour of something different', () => {
    const dup = vec.normalize([1, 0, 0, 0]);
    const dup2 = vec.normalize([0.99, 0.01, 0, 0]);
    const dup3 = vec.normalize([0.98, 0.02, 0, 0]);
    const other = vec.normalize([0, 1, 0, 0]);
    // Scores close together, as fused RRF scores in a real candidate set are.
    const picked = vec.mmr([
      { id: 'a', score: 1.00, vec: dup },
      { id: 'b', score: 0.98, vec: dup2 },
      { id: 'c', score: 0.97, vec: dup3 },
      { id: 'd', score: 0.85, vec: other },
    ], { lambda: 0.7, k: 2 });
    eq(picked[0].id, 'a', 'the most relevant item leads');
    eq(picked[1].id, 'd', 'the second slot should go to the distinct item, not a duplicate');
  });

  it('MMR still respects relevance when nothing is redundant', () => {
    const orthogonal = (i) => {
      const v = new Float32Array(4);
      v[i] = 1;
      return v;
    };
    const picked = vec.mmr([
      { id: 'a', score: 1.0, vec: orthogonal(0) },
      { id: 'b', score: 0.9, vec: orthogonal(1) },
      { id: 'c', score: 0.8, vec: orthogonal(2) },
    ], { lambda: 0.7, k: 3 });
    eq(picked.map((p) => p.id).join(','), 'a,b,c', 'with no redundancy, order should follow relevance');
  });

  it('MMR does not divide by zero when every score is zero', () => {
    const picked = vec.mmr([
      { id: 'a', score: 0, vec: vec.normalize([1, 0]) },
      { id: 'b', score: 0, vec: vec.normalize([0, 1]) },
    ], { lambda: 0.7, k: 2 });
    eq(picked.length, 2);
    assert(picked.every((p) => p.id), 'should still return both items');
  });
});

// ================= chunking =================

describe('Chunking', () => {
  it('covers every character of the document', () => {
    const doc = filler(60, 'coverage');
    const chunks = text.chunkText(doc);
    gt(chunks.length, 1, 'a long document should produce several chunks');
    // Walk the chunks and confirm the union is the whole range.
    let reach = 0;
    for (const c of chunks) {
      assert(c.start <= reach, `gap in coverage before offset ${c.start} (reached ${reach})`);
      reach = Math.max(reach, c.end);
    }
    eq(reach, doc.length, 'coverage must extend to the final character');
    eq(chunks[0].start, 0, 'coverage must start at zero');
    return `${chunks.length} chunks over ${doc.length} chars`;
  });

  it('chunk text matches the source slice exactly', () => {
    const doc = filler(40, 'slices');
    for (const c of text.chunkText(doc)) {
      eq(c.text, doc.slice(c.start, c.end), `chunk ${c.i} text should equal its slice`);
    }
  });

  it('respects the size ceiling', () => {
    const doc = filler(80, 'ceiling');
    for (const c of text.chunkText(doc, { target: 800, max: 1200 })) {
      assert(c.end - c.start <= 1200, `chunk ${c.i} is ${c.end - c.start} chars, over the 1200 ceiling`);
    }
  });

  it('consecutive chunks overlap so facts on a boundary survive', () => {
    const doc = filler(40, 'overlap');
    const chunks = text.chunkText(doc);
    let overlaps = 0;
    for (let i = 1; i < chunks.length; i++) {
      if (chunks[i].start < chunks[i - 1].end) overlaps++;
    }
    gt(overlaps, 0, 'at least some chunks should overlap');
    return `${overlaps}/${chunks.length - 1} boundaries overlap`;
  });

  it('force-splits a run with no sentence boundaries', () => {
    const wall = 'x'.repeat(9000);
    const chunks = text.chunkText(wall, { target: 1000, max: 1400 });
    gt(chunks.length, 4, 'an unbroken wall of text must still be split');
    for (const c of chunks) assert(c.end - c.start <= 1400, 'force-split chunk over ceiling');
    let reach = 0;
    for (const c of chunks) reach = Math.max(reach, c.end);
    eq(reach, wall.length, 'force-split must still cover everything');
  });

  it('leaves a short document as a single chunk', () => {
    const chunks = text.chunkText('One short paragraph, nothing more.');
    eq(chunks.length, 1);
    eq(chunks[0].start, 0);
  });

  it('handles an empty document without throwing', () => {
    eq(text.chunkText('').length, 0);
  });
});

// ================= on-device embedder =================

describe('On-device embedder', () => {
  it('is deterministic across calls', () => {
    const a = local.embed('perovskite solar cells degrade under thermal stress');
    const b = local.embed('perovskite solar cells degrade under thermal stress');
    for (let i = 0; i < a.length; i++) eq(a[i], b[i], `component ${i} differs between runs`);
  });

  it('produces unit vectors', () => {
    const v = local.embed('the mitochondrion is the powerhouse of the cell');
    close(Math.sqrt(v.reduce((s, x) => s + x * x, 0)), 1, 1e-5);
  });

  it('scores related text above unrelated text', () => {
    const q = local.embed('spaced repetition improves long term memory retention');
    const related = local.embed('reviewing material at expanding intervals strengthens memory retention over the long term');
    const unrelated = local.embed('the harbour ferry timetable changes on public holidays in winter');
    gt(vec.dot(q, related), vec.dot(q, unrelated), 'related text should score higher');
    return `related ${vec.dot(q, related).toFixed(3)} vs unrelated ${vec.dot(q, unrelated).toFixed(3)}`;
  });

  it('gives partial credit for shared morphology', () => {
    const a = local.embed('mitochondria');
    const b = local.embed('mitochondrial');
    const c = local.embed('bicycle');
    gt(vec.dot(a, b), vec.dot(a, c), 'character n-grams should link word forms');
    return `mitochondria~mitochondrial ${vec.dot(a, b).toFixed(3)}, ~bicycle ${vec.dot(a, c).toFixed(3)}`;
  });

  it('is identified as a lexical space so fusion can down-weight it', () => {
    assert(local.isLexicalSpace(LOCAL_SPACE), 'local space should report as lexical');
    assert(!local.isLexicalSpace('openai:1536'), 'a learned space should not');
  });

  it('an empty string yields a zero vector rather than NaN', () => {
    const v = local.embed('');
    assert(v.every((x) => x === 0), 'should be all zeros');
  });
});

// ================= index persistence =================

describe('Index persistence', () => {
  it('survives a reload from IndexedDB with vectors intact', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'p1', title: 'Perovskite degradation', body: 'Heat above sixty degrees drives perovskite degradation faster than light exposure alone.', summary: 'Heat drives degradation.' });
    await seed({ id: 'p2', title: 'Harbour ferry timetable', body: 'The winter ferry timetable adds two sailings on public holidays.', summary: 'Ferry timetable changes.' });
    await index.flush();

    const before = await index.searchVectors(local.embed('perovskite degradation heat'), { k: 2 });

    // Drop all in-memory state and reload purely from storage. This is what
    // exercises the structured clone of the packed Int8Array shards.
    index._reset();
    await index.load();

    const after = await index.searchVectors(local.embed('perovskite degradation heat'), { k: 2 });
    eq(after[0].id, before[0].id, 'top hit should be identical after reload');
    close(after[0].score, before[0].score, 1e-6, 'scores should survive the round trip exactly');
    return `top hit ${after[0].id} at ${after[0].score.toFixed(4)}`;
  });

  it('BM25 ranks the document containing a rare term first', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'b1', title: 'Cell respiration notes', body: 'Glycolysis converts glucose to pyruvate in the cytoplasm before the Krebs cycle begins.', summary: 'Glycolysis overview.' });
    await seed({ id: 'b2', title: 'Ferry timetable', body: 'Sailings depart hourly from the north quay during summer months.', summary: 'Timetable.' });
    await seed({ id: 'b3', title: 'General science', body: 'Science covers many subjects including chemistry and physics and biology broadly.', summary: 'Science overview.' });
    await index.flush();

    const hits = await index.searchLexical('glycolysis pyruvate');
    gt(hits.length, 0, 'BM25 should return something');
    eq(hits[0].id, 'b1', 'the document with the rare terms should rank first');
    return `${hits.length} hits, top = ${hits[0].id} (${hits[0].score.toFixed(3)})`;
  });

  it('BM25 does not score documents that lack the query terms', async () => {
    const hits = await index.searchLexical('glycolysis');
    assert(hits.every((h) => h.id === 'b1'), 'only the matching document should score');
  });

  it('removing a document takes it out of both retrieval arms', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'r1', title: 'Removable document', body: 'This document mentions xenobiology exactly once for the purposes of the test.', summary: 'Xenobiology mention.' });
    await seed({ id: 'r2', title: 'Keeper', body: 'A different document about ordinary matters that will remain in the index.', summary: 'Ordinary.' });
    await index.flush();

    gt((await index.searchLexical('xenobiology')).length, 0, 'should be findable before removal');
    await store.remove('r1');
    index._reset();
    await index.load();

    eq((await index.searchLexical('xenobiology')).length, 0, 'should be gone from BM25');
    const vhits = await index.searchVectors(local.embed('xenobiology'), { k: 5 });
    assert(!vhits.some((h) => h.id === 'r1'), 'should be gone from the vector arm');
  });

  it('a deleted document does not lend its vocabulary to the next one saved', async () => {
    // Regression: ordinals used to be recycled while postings kept pointing at
    // them, so the next document saved inherited the deleted one's entire
    // vocabulary — and was then cited as evidence for it.
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'gone', title: 'Kubernetes ingress notes', body: 'Notes on configuring a kubernetes ingress controller and its annotations.', summary: 'Kubernetes ingress configuration.' });
    await index.flush();
    await store.remove('gone');

    await seed({ id: 'fresh', title: 'Slow braised tomato sauce', body: 'A method for slow braised tomato sauce with garlic, basil and good olive oil.', summary: 'Tomato sauce method.' });
    await index.flush();

    const hits = await index.searchLexical('kubernetes ingress');
    assert(!hits.some((h) => h.id === 'fresh'),
      `the cooking note must not match the deleted page's terms; got ${hits.map((h) => h.id).join(', ') || 'nothing'}`);
    eq(hits.length, 0, 'nothing should match a deleted document’s vocabulary');

    // And the new document is still findable on its own terms.
    const own = await index.searchLexical('braised tomato sauce');
    eq(own[0]?.id, 'fresh', 'the new document should still be retrievable');
  });

  it('re-indexing drops the words a document no longer contains', async () => {
    // Deepening rewrites title-only memories into full ones constantly, so a
    // stale-vocabulary bug here would be permanent and widespread.
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'evolving', title: 'Placeholder about zeppelins', body: 'An early draft mentioning zeppelins and airship mooring masts throughout.', summary: 'Zeppelin draft.' });
    await index.flush();
    gt((await index.searchLexical('zeppelins')).length, 0, 'findable before the rewrite');

    // Same id, entirely different content — exactly what deepen() produces.
    await seed({ id: 'evolving', title: 'Perovskite stability under stress', body: 'The rewritten document covers perovskite stability under thermal stress only.', summary: 'Perovskite stability.' });
    await index.flush();

    eq((await index.searchLexical('zeppelins')).length, 0, 'the old vocabulary should be gone');
    eq((await index.searchLexical('perovskite stability'))[0]?.id, 'evolving', 'the new vocabulary should match');
  });

  it('a vector shard in an old format is dropped rather than misread', async () => {
    // The dangerous version of this bug is silent: rows load with scale 0,
    // score 0, and topK still fills its buffer — handing the oldest memories
    // to fusion at full weight as "semantic" matches.
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'v1', title: 'Tidal turbines', body: 'Tidal turbines convert marine currents into electricity using submerged rotors.', summary: 'Tidal turbines.' });
    await seed({ id: 'v2', title: 'Ferry timetable', body: 'Winter sailings depart hourly from the north quay on weekdays.', summary: 'Ferry timetable.' });
    await index.flush();
    gt((await index.stats()).withVectors, 0, 'vectors should be present to begin with');

    // Rewrite the shards as an older build would have: no format, no scales.
    const shards = await store.shardAll();
    await store.shardPutMany(shards.map((sh) => {
      const { format, scales, ...rest } = sh;
      return rest;
    }));

    index._reset();
    await index.load();
    const st = await index.stats();
    eq(st.withVectors, 0, 'unrecognised shards must not be treated as usable vectors');
    gt(st.pendingReembed, 0, 'they should be queued for re-embedding instead');

    // And the failure is visible to the caller rather than silent.
    const hits = await search.search('tidal turbines marine energy', { limit: 3 });
    assert(hits.every((h) => h.semantic === 0), 'no similarity may be reported from dropped vectors');
    if (hits.length) assert(hits[0].semanticSkipped, 'the caller should be told why');
    return `dropped cleanly; ${st.pendingReembed} queued for re-embed`;
  });

  it('an interrupted rebuild recovers instead of destroying the index', async () => {
    // Compaction must clear vectors and postings before rewriting them,
    // because renumbering ordinals invalidates every posting at once. It runs
    // on an alarm inside an MV3 service worker, which Chrome terminates after
    // 30s idle — so the half-finished state is reachable in normal use, and
    // silently losing the entire search index would be unrecoverable.
    await freshDb();
    await useLocalProvider();
    for (let i = 0; i < 5; i++) {
      await seed({ id: `k${i}`, title: `Document ${i} on turbine bearings`, body: `Text for document ${i} about turbine bearing wear and lubrication intervals.`, summary: `Doc ${i}.` });
    }
    await index.flush();
    const healthy = (await index.searchLexical('turbine bearings')).length;
    eq(healthy, 5, 'all five should be findable to begin with');

    // Simulate the worker dying mid-rebuild: the marker is set and the
    // vector/postings stores are wiped, exactly as compact() leaves them
    // between the clear and the first flush.
    await store.metaSet('indexRebuildInProgress', { startedAt: Date.now(), before: 5 });
    await store.shardClear();
    await store.postingsClear();

    index._reset();
    await index.load();

    eq((await index.searchLexical('turbine bearings')).length, 5,
      'the index must reconstruct itself from the memory and chunk stores');
    const sem = await index.searchVectors(local.embed('turbine bearing lubrication'), { k: 5 });
    gt(sem.length, 0, 'vectors should be restored too, with no re-embedding');
    eq(await store.metaGet('indexRebuildInProgress', null), null,
      'the marker should be cleared once recovery succeeds');
    return 'index fully reconstructed after a simulated worker kill';
  });

  it('a read-only context leaves a broken index alone instead of finishing it off', async () => {
    // rebuildIndexFromStores clears the vector and postings stores before
    // rewriting them, and store.* is not gated by the read-only flag. Without
    // an explicit bail, merely opening the dashboard while the worker's
    // compaction had been interrupted would wipe both stores and then fail on
    // the first write — converting a recoverable state into a dead one.
    await freshDb();
    await useLocalProvider();
    for (let i = 0; i < 4; i++) {
      await seed({ id: `ro${i}`, title: `Read-only doc ${i} on turbine seals`, body: `Body ${i} about turbine seal inspection and replacement.`, summary: `Doc ${i}.` });
    }
    await index.flush();
    await store.metaSet('indexRebuildInProgress', { startedAt: Date.now() });

    index._reset();
    index.setReadOnly(true);
    try {
      await index.load();
      // The marker must survive so the writer can still repair it.
      assert(await store.metaGet('indexRebuildInProgress', null),
        'a read-only context must not clear the repair marker');
      const shards = await store.shardAll();
      gt(shards.length, 0, 'a read-only context must not clear the vector store');
    } finally {
      index.setReadOnly(false);
    }

    // The writer then repairs it normally.
    index._reset();
    await index.load();
    eq((await index.searchLexical('turbine seals')).length, 4, 'the writer should recover all four');
    eq(await store.metaGet('indexRebuildInProgress', null), null, 'and clear the marker');
    return 'read-only context deferred repair; writer completed it';
  });

  it('a rebuild that throws destroys nothing and keeps its marker', async () => {
    // Two invariants at once, both of which were broken:
    //   - assertWritable must run before the first destructive call, not after
    //   - a throw must leave the marker in place; clearing it in a `finally`
    //     discarded the only signal that the index still needed rebuilding,
    //     at exactly the moment it did
    // A read-only caller is the cheapest way to make the rebuild throw through
    // a real code path rather than a stub.
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'rt1', title: 'Retry document about turbines', body: 'A document about turbine retry semantics and recovery behaviour.', summary: 'Retry doc.' });
    await index.flush();
    const shardsBefore = (await store.shardAll()).length;
    gt(shardsBefore, 0, 'there should be shards to protect');
    await store.metaSet('indexRebuildInProgress', { startedAt: Date.now(), attempt: 1 });

    index.setReadOnly(true);
    let threw = false;
    try {
      await index.rebuildIndexFromStores();
    } catch {
      threw = true;
    } finally {
      index.setReadOnly(false);
    }

    assert(threw, 'a read-only rebuild must refuse rather than proceed');
    eq((await store.shardAll()).length, shardsBefore,
      'it must refuse BEFORE clearing the vector store, not after');
    assert(await store.metaGet('indexRebuildInProgress', null),
      'the marker must survive the failure so a later attempt can retry');

    // A writable retry then completes and clears the marker.
    index._reset();
    await index.load();
    eq((await index.searchLexical('turbine retry')).length, 1, 'the retry should rebuild the index');
    eq(await store.metaGet('indexRebuildInProgress', null), null, 'and clear the marker on success');
    return 'nothing destroyed, marker preserved, retry succeeded';
  });

  it('gives up rather than boot-looping on a rebuild that never succeeds', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'loop1', title: 'Loop guard document', body: 'A document used to verify the recovery attempt ceiling behaviour.', summary: 'Loop guard.' });
    await index.flush();
    // Already past the ceiling.
    await store.metaSet('indexRebuildInProgress', { startedAt: Date.now(), attempt: 99 });

    index._reset();
    await index.load();
    eq(await store.metaGet('indexRebuildInProgress', null), null,
      'the marker should be cleared rather than retried forever');
  });

  it('the re-embed queue rotates instead of re-selecting the same head', async () => {
    // pendingReembedIds reads from the front of a Set, and Set.add on an
    // existing member does not move it. A document that cannot be satisfied
    // therefore re-selected itself on every pass — a busy-loop of *paid*
    // embedding calls once the background drain existed to consume the queue.
    await freshDb();
    await useLocalProvider();
    await index.load();
    for (let i = 0; i < 3; i++) {
      await index.addDoc({
        id: `q${i}`, vec: local.embed(`queue document ${i}`), space: LOCAL_SPACE,
        createdAt: Date.now(), chunks: [], tokensText: `queue document ${i}`,
      });
    }
    // Re-adding in a foreign space queues each one.
    for (let i = 0; i < 3; i++) {
      await index.addDoc({
        id: `q${i}`, vec: local.embed(`queue document ${i}`), space: 'openai:1536',
        createdAt: Date.now(), chunks: [], tokensText: `queue document ${i}`,
      });
    }
    await index.flush();
    const first = await index.pendingReembedIds(2);
    eq(first.length, 2, 'two should be queued at the head');

    // Re-queue the head; it must move to the back, not stay in place.
    await index.addDoc({
      id: first[0], vec: local.embed('queue document 0'), space: 'openai:1536',
      createdAt: Date.now(), chunks: [], tokensText: 'queue document 0',
    });
    await index.flush();
    const second = await index.pendingReembedIds(2);
    assert(second[0] !== first[0],
      `the head must rotate; got ${first[0]} twice, which is the busy-loop`);
    return `head moved ${first[0]} → ${second[0]}`;
  });

  it('deleted memories are dropped from the re-embed queue rather than starving it', async () => {
    await freshDb();
    await useLocalProvider();
    await index.load();
    // The first vector written defines the index's space, so a document has
    // to establish it before another can mismatch it.
    await index.addDoc({
      id: 'anchor', vec: local.embed('anchor document'), space: LOCAL_SPACE,
      createdAt: Date.now(), chunks: [], tokensText: 'anchor document',
    });
    await index.addDoc({
      id: 'ghost', vec: local.embed('ghost document'), space: 'openai:1536',
      createdAt: Date.now(), chunks: [], tokensText: 'ghost document',
    });
    await index.flush();
    gt((await index.pendingReembedIds(10)).length, 0, 'should be queued');
    eq(await index.dropFromReembedQueue(['ghost']), 1, 'should drop cleanly');
    eq((await index.pendingReembedIds(10)).length, 0, 'and leave the queue empty');
  });

  it('a re-embedded vector survives compaction', async () => {
    // The chunk record is the source of truth for every rebuild path, so a
    // re-embed that updated only the packed matrix was reverted by the next
    // compaction — and if the stored space was stale, addDoc re-queued the
    // document, making the drain and compaction passes feed each other.
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'rv1', title: 'Vector survival document', body: 'A document about vector survival across index compaction.', summary: 'Vector survival.' });
    await seed({ id: 'rv2', title: 'Second document', body: 'Another document so compaction has something to keep.', summary: 'Second.' });
    await index.flush();

    // Simulate what the drain does: new vector into both the matrix and the
    // chunk record.
    const fresh = local.embed('a deliberately different vector for the survival test');
    await store.updateChunkVector('rv1', { docVec: fresh, space: LOCAL_SPACE });
    await index.addDoc({
      id: 'rv1', vec: fresh, space: LOCAL_SPACE, createdAt: Date.now(),
      chunks: null, tokensText: 'Vector survival document',
    }, { writeChunks: false });
    await index.flush();

    const rec = await store.getChunks('rv1');
    gt(rec.count, 0, 'existing passages must be preserved by the vector update');

    // Force a compaction and confirm the new vector is what comes back.
    await store.remove('rv2');
    await index.compact();

    const after = await store.getChunks('rv1');
    close(vec.dot(after.docVec, vec.normalize(fresh)), 1, 1e-4,
      'compaction must preserve the re-embedded vector, not revert it');
    const st = await index.stats();
    eq(st.pendingReembed, 0, 'and must not re-queue the document it just rebuilt');
    return 'vector and passages both survived compaction';
  });

  it('changing a document’s space invalidates its passage vectors', async () => {
    // The chunk record has ONE space field, and retrieval treats it as proof
    // that the whole passage matrix is comparable to the query vector — then
    // votes the best passage at the heaviest weight in the fusion and cites it
    // as "the part that matched". Re-stamping the space while keeping passages
    // embedded by a different model therefore makes a memory cite an arbitrary
    // passage, which is worse than citing none.
    await freshDb();
    await useLocalProvider();
    await seed({
      id: 'sp1', title: 'Space change document',
      body: filler(20, 'spacechange'),
      summary: 'A document with several passages embedded in the local space.',
    });
    await index.flush();

    const before = await store.getChunks('sp1');
    gt(before.count, 1, 'should start with several passage vectors');
    eq(before.space, LOCAL_SPACE);

    // A same-space update must preserve the passages.
    await store.updateChunkVector('sp1', { docVec: local.embed('same space update'), space: LOCAL_SPACE });
    const same = await store.getChunks('sp1');
    eq(same.count, before.count, 'a same-space update must keep the passage vectors');
    eq(same.texts.length, before.texts.length, 'and their text');

    // A cross-space update must not leave passages from the old model behind
    // wearing the new space's label.
    await store.updateChunkVector('sp1', { docVec: local.embed('cross space update'), space: 'openai:1536' });
    const after = await store.getChunks('sp1');
    eq(after.space, 'openai:1536', 'the space should be updated');
    eq(after.count, 0, 'passage vectors from the old space must be invalidated');
    eq(after.data.length, 0, 'and the matrix emptied');
    eq(after.texts.length, before.texts.length, 'but the passage TEXT is still good and should survive');
    assert(after.docVec, 'the new document vector should be stored');
    return `${before.count} passages invalidated on space change, ${after.texts.length} texts kept`;
  });

  it('retrieval skips the passage tier for a document whose passages were invalidated', async () => {
    // count === 0 is what makes search ignore the stale matrix.
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'sk1', title: 'Skip tier document', body: filler(20, 'skiptier'), summary: 'A document about the skip tier behaviour.' });
    await seed({ id: 'sk2', title: 'Control document', body: filler(20, 'control'), summary: 'A control document that keeps its passages.' });
    await index.flush();

    await store.updateChunkVector('sk1', { docVec: local.embed('skip tier document'), space: LOCAL_SPACE });
    const rec = await store.getChunks('sk1');
    gt(rec.count, 0, 'same-space update keeps passages, so this control still has them');

    // Now invalidate and confirm retrieval doesn't produce evidence from the
    // dropped matrix.
    await store.updateChunkVector('sk1', { docVec: local.embed('skip tier document'), space: 'other:1536' });
    await store.updateChunkVector('sk1', { docVec: local.embed('skip tier document'), space: LOCAL_SPACE });
    const hits = await search.search('skiptier overview background material', { limit: 3 });
    const hit = hits.find((h) => h.memory.id === 'sk1');
    if (hit) assert(hit.evidence === null, 'a document with no passage vectors must not fabricate an evidence passage');
    return hit ? 'retrieved with no evidence passage, as expected' : 'not retrieved; no stale evidence possible';
  });

  it('a zero vector never claims to be searchable', async () => {
    // scanPacked skips a zero-scale row, but topK fills its buffer regardless
    // of score — so a row that claims a vector enters the semantic list at
    // 0.0, ahead of every genuinely negative match, and RRF ranks by position.
    await freshDb();
    await useLocalProvider();
    await index.load();
    await index.addDoc({
      id: 'zero',
      vec: new Float32Array(1536),          // e.g. an all-zero embedding from an import
      space: LOCAL_SPACE,
      createdAt: Date.now(),
      chunks: [],
      tokensText: 'a document whose embedding is entirely zero',
    });
    await index.flush();
    const st = await index.stats();
    eq(st.withVectors, 0, 'a zero vector must not count as a usable vector');
    const hits = await index.searchVectors(local.embed('anything at all'), { k: 5 });
    assert(!hits.some((h) => h.id === 'zero'), 'it must not appear in the semantic list');
  });

  it('compaction reclaims tombstoned ordinals without losing anything', async () => {
    await freshDb();
    await useLocalProvider();
    for (let i = 0; i < 6; i++) {
      await seed({ id: `c${i}`, title: `Document number ${i} about turbines`, body: `Body text for document ${i} covering turbine maintenance schedules.`, summary: `Doc ${i}.` });
    }
    await index.flush();
    for (const id of ['c1', 'c3', 'c4']) await store.remove(id);

    const before = await index.stats();
    gt(await index.tombstoneRatio(), 0, 'there should be tombstones to reclaim');

    const res = await index.compact();
    assert(res.compacted, 'compaction should have run');
    const after = await index.stats();
    eq(after.docs, 3, 'the surviving documents should all still be there');
    eq(await index.tombstoneRatio(), 0, 'no tombstones should remain');
    assert(after.ordinals < before.ordinals, 'the ordinal table should have shrunk');

    const hits = await index.searchLexical('turbine maintenance');
    eq(hits.length, 3, 'all survivors remain lexically findable');
    const sem = await index.searchVectors(local.embed('turbine maintenance schedules'), { k: 5 });
    gt(sem.length, 0, 'vectors should survive compaction without re-embedding');
    return `${before.ordinals} → ${after.ordinals} ordinals, 3 docs intact`;
  });

  it('time filtering happens in the index, without reading records', async () => {
    await freshDb();
    await useLocalProvider();
    const now = Date.now();
    const DAY = 86400000;
    await seed({ id: 't-today', title: 'Read today', body: 'Something read today about ordinary matters.', summary: 'Today.', createdAt: now - 3600000 });
    await seed({ id: 't-yest', title: 'Read yesterday', body: 'Something read yesterday about ordinary matters.', summary: 'Yesterday.', createdAt: now - 30 * 3600000 });
    await seed({ id: 't-old', title: 'Read last month', body: 'Something read a while ago about ordinary matters.', summary: 'Old.', createdAt: now - 40 * DAY });
    await index.flush();

    const yesterday = await index.idsBetween(now - 48 * 3600000, now - 24 * 3600000);
    eq(yesterday.length, 1);
    eq(yesterday[0], 't-yest');
  });
});

// ================= the headline test =================

describe('Buried facts in long documents', () => {
  // This is the failure the whole rewrite exists to fix. A long document used
  // to get one embedding computed over its title plus the first 2,000
  // characters, so anything past that point could not be retrieved by meaning
  // no matter how the question was phrased.
  const MARKER = 'The anomalous readings were traced to a miscalibrated thermocouple in bay seven.';
  let doc, buriedAt;

  it('sets up a long document with a distinctive fact near the end', () => {
    const head = filler(30, 'introductory');
    const tail = filler(10, 'closing');
    doc = `${head}\n\n${MARKER}\n\n${tail}`;
    buriedAt = doc.indexOf(MARKER);
    gt(buriedAt, 12000, 'the marker must sit well past any document-level embedding window');
    return `${doc.length} chars, marker at offset ${buriedAt}`;
  });

  it('a document-level embedding alone cannot find the buried fact', () => {
    // Reproduce the old behaviour exactly: embed title + first 2,000 chars.
    const oldStyle = local.embed(`Field report\n\n${doc.slice(0, 2000)}`);
    const query = local.embed('miscalibrated thermocouple bay seven anomalous readings');
    const sim = vec.dot(oldStyle, query);
    assert(sim < 0.2, `old-style embedding scored ${sim.toFixed(4)} — expected near zero`);
    return `document-level similarity to the question: ${sim.toFixed(4)}`;
  });

  it('the chunk containing the fact matches far better than the document does', () => {
    const chunks = text.chunkText(doc);
    const query = local.embed('miscalibrated thermocouple bay seven anomalous readings');
    const docLevel = vec.dot(local.embed(`Field report\n\n${doc.slice(0, 2000)}`), query);

    let best = -1, bestI = -1;
    chunks.forEach((c, i) => {
      const s = vec.dot(local.embed(`Field report\n\n${c.text}`), query);
      if (s > best) { best = s; bestI = i; }
    });

    assert(chunks[bestI].text.includes('thermocouple'),
      'the best-matching chunk should be the one containing the fact');
    // The absolute number depends on the embedder; the ratio is the claim.
    gt(best / Math.max(docLevel, 1e-6), 3,
      `chunk similarity ${best.toFixed(4)} was not meaningfully better than document-level ${docLevel.toFixed(4)}`);
    return `chunk #${bestI} of ${chunks.length}: ${best.toFixed(4)} vs document-level ${docLevel.toFixed(4)} — ${(best / docLevel).toFixed(1)}× better`;
  });

  it('end-to-end retrieval returns the fact as evidence', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'long', title: 'Field report', body: doc, summary: 'A long field report covering routine observations.' });
    // Decoys that are plausible neighbours but do not contain the fact.
    await seed({ id: 'decoy1', title: 'Equipment manual', body: filler(20, 'equipment'), summary: 'Equipment handling manual.' });
    await seed({ id: 'decoy2', title: 'Weekly notes', body: filler(20, 'weekly'), summary: 'Notes from the week.' });
    await index.flush();

    const hits = await search.search('miscalibrated thermocouple in bay seven', { limit: 3 });
    gt(hits.length, 0, 'retrieval returned nothing');
    eq(hits[0].memory.id, 'long', 'the long document should rank first');
    assert(hits[0].evidence, 'the hit should carry an evidence passage');
    assert(hits[0].evidence.includes('thermocouple'),
      `evidence should contain the buried fact, got: ${hits[0].evidence.slice(0, 160)}…`);
    return `evidence passage starts at char ${hits[0].evidenceStart} and contains the fact`;
  });

  it('the evidence handed to the model is the matched passage, not the opening', async () => {
    const hits = await search.search('miscalibrated thermocouple in bay seven', { limit: 1 });
    const ctx = ai.formatContext([{ ...hits[0].memory, evidence: hits[0].evidence }]);
    assert(ctx.includes('Matched passage'), 'context should be built from the matched passage');
    assert(ctx.includes('thermocouple'), 'the fact must reach the model');
    assert(!ctx.startsWith('[#1] (just now [web] [title-only]'), 'should not be treated as title-only');
  });
});

// ================= hybrid retrieval behaviour =================

describe('Hybrid retrieval', () => {
  it('finds a document by exact rare term even with no semantic overlap', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'h1', title: 'Release notes', body: 'Version 4.2 fixes the zzyzx regression that affected sorting.', summary: 'Fixes the zzyzx regression.' });
    await seed({ id: 'h2', title: 'Other notes', body: filler(6, 'other'), summary: 'Unrelated notes.' });
    await index.flush();
    const hits = await search.search('zzyzx', { limit: 3 });
    eq(hits[0].memory.id, 'h1');
  });

  it('diversifies away from near-duplicate captures of the same page', async () => {
    await freshDb();
    await useLocalProvider();
    const body = 'Perovskite solar cells reach record efficiency but degrade under heat, moisture and ultraviolet exposure over time.';
    // Six history rows for effectively the same article, plus one distinct
    // document that is genuinely relevant.
    for (let i = 0; i < 6; i++) {
      await seed({ id: `dup${i}`, title: `Perovskite stability report`, body, summary: 'Perovskite cells degrade under heat.', sourceKind: 'history', createdAt: Date.now() - i * 60000 });
    }
    await seed({ id: 'distinct', title: 'Encapsulation strategies for solar cells', body: 'New encapsulation approaches extend operational lifetime of solar modules past one thousand hours under stress.', summary: 'Encapsulation extends module lifetime.' });
    await index.flush();

    const hits = await search.search('how do perovskite solar cells degrade and what extends their lifetime', { limit: 4 });
    const ids = hits.map((h) => h.memory.id);
    assert(ids.includes('distinct'), `MMR should surface the distinct document; got ${ids.join(', ')}`);
    const dupCount = ids.filter((id) => id.startsWith('dup')).length;
    assert(dupCount < 4, `too many duplicates survived: ${dupCount} of ${ids.length}`);
    return `results: ${ids.join(', ')}`;
  });

  it('restricts a time-anchored question to its window', async () => {
    await freshDb();
    await useLocalProvider();
    const now = Date.now();
    await seed({ id: 'y1', title: 'Yesterday reading', body: 'A document about ordinary subjects read yesterday afternoon.', summary: 'Read yesterday.', createdAt: now - 30 * 3600000 });
    await seed({ id: 'o1', title: 'Older reading', body: 'A document about ordinary subjects read several weeks ago.', summary: 'Read weeks ago.', createdAt: now - 20 * 86400000 });
    await index.flush();

    const hits = await search.search('what did I read yesterday', { limit: 5 });
    gt(hits.length, 0, 'should find something in the window');
    assert(hits.every((h) => h.memory.id === 'y1'), `only yesterday's item should appear, got ${hits.map((h) => h.memory.id).join(', ')}`);
  });

  it('returns nothing rather than the wrong week when a window is empty', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'old-only', title: 'Ancient note', body: 'Something from long ago about ordinary matters.', summary: 'Long ago.', createdAt: Date.now() - 90 * 86400000 });
    await index.flush();
    const hits = await search.search('what did I read yesterday', { limit: 5 });
    eq(hits.length, 0, 'an empty window must not fall back to unrelated results');
  });

  it('quarantines a document embedded by a different model', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'native', title: 'Native space document', body: 'A document about tidal turbines indexed in the local embedding space.', summary: 'Tidal turbines.' });
    await index.flush();
    eq((await index.stats()).space, LOCAL_SPACE, 'index should have adopted the local space');

    // A vector claiming to come from a different model must not enter the
    // matrix — cosine across embedding spaces is meaningless.
    await index.addDoc({
      id: 'foreign',
      vec: local.embed('a document about tidal turbines from another model entirely'),
      space: 'openai:1536',
      createdAt: Date.now(),
      chunks: [],
      tokensText: 'a document about tidal turbines from another model entirely',
    });
    await index.flush();

    const stats = await index.stats();
    eq(stats.pendingReembed, 1, 'the foreign document should be queued for re-embedding');
    const sem = await index.searchVectors(local.embed('tidal turbines'), { k: 5 });
    assert(!sem.some((h) => h.id === 'foreign'), 'the foreign vector must not be scored');
    assert(sem.some((h) => h.id === 'native'), 'the native vector should still rank');

    // BM25 still covers it, so the document is findable, just not by meaning.
    const lex = await index.searchLexical('tidal turbines');
    assert(lex.some((h) => h.id === 'foreign'), 'BM25 should still cover the quarantined document');
    return `foreign document queued for re-embed, still lexically findable`;
  });

  it('recovers quarantined vectors when the space is switched back', async () => {
    // Chunk records carry their own space tag, so switching the active space
    // restores every document that already had a vector in it — no re-embedding
    // and no API calls for those.
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'sp1', title: 'Space switch document', body: 'A document about marine energy stored with its own space tag.', summary: 'Marine energy.' });
    await index.flush();

    await index.setSpace('openai:1536');
    let stats = await index.stats();
    eq(stats.withVectors, 0, 'nothing should be searchable in a space it was not embedded in');
    eq(stats.pendingReembed, 1);

    await index.setSpace(LOCAL_SPACE);
    stats = await index.stats();
    eq(stats.withVectors, 1, 'the vector should be restored from the chunk record');
    eq(stats.pendingReembed, 0);
    const sem = await index.searchVectors(local.embed('marine energy'), { k: 3 });
    eq(sem[0].id, 'sp1');
    return 'vector restored from storage with no re-embedding';
  });

  it('reports when the semantic arm was skipped', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'skip1', title: 'Skip reporting', body: 'A document about hydrothermal vents used to check skip reporting.', summary: 'Hydrothermal vents.' });
    await index.flush();
    // Force the index into a space the current provider cannot query.
    await index.setSpace('openai:1536');

    const hits = await search.search('hydrothermal vents', { limit: 3 });
    assert(hits.every((h) => h.semantic === 0), 'no cross-space semantic scores may appear');
    gt(hits.length, 0, 'BM25 should still return the document');
    assert(hits[0].semanticSkipped, 'the reason for skipping should be reported to the caller');
    return `lexical-only fallback engaged: ${hits[0].semanticSkipped}`;
  });
});

// ================= ingest =================

describe('Ingest pipeline', () => {
  it('chunks a long page and stores a passage vector for each chunk', async () => {
    await freshDb();
    await useLocalProvider();
    const body = filler(40, 'ingested');
    await ingestMod.ingest({
      url: 'https://example.test/long-ingest',
      title: 'Long ingested page',
      text: body,
      sourceKind: 'web',
    });
    const id = await store.urlId('https://example.test/long-ingest');
    const rec = await store.getChunks(id);
    assert(rec, 'chunk record should exist');
    gt(rec.count, 1, 'a long page should produce multiple passages');
    eq(rec.data.length, rec.count * rec.dim, 'packed passage matrix should be exactly count × dim');
    eq(rec.space, LOCAL_SPACE);
    // Every passage vector should be non-zero and unit length.
    for (let i = 0; i < rec.count; i++) {
      const v = rec.data.subarray(i * rec.dim, (i + 1) * rec.dim);
      close(Math.sqrt(v.reduce((s, x) => s + x * x, 0)), 1, 1e-4, `passage ${i} should be normalised`);
    }
    return `${rec.count} passages stored, ${rec.dim} dims each`;
  });

  it('re-ingesting unchanged content skips the pipeline entirely', async () => {
    const url = 'https://example.test/unchanged';
    const body = filler(10, 'unchanged');
    const first = await ingestMod.ingest({ url, title: 'Unchanged page', text: body, sourceKind: 'web' });
    const second = await ingestMod.ingest({ url, title: 'Unchanged page', text: body, sourceKind: 'web' });
    eq(second.id, first.id, 'should update in place, not duplicate');
    eq(second.createdAt, first.createdAt, 'original capture time should be preserved');
    gt(second.updatedAt, 0, 'updatedAt should be set');
  });

  it('the same URL never produces two memories', async () => {
    const before = await store.count();
    await ingestMod.ingest({ url: 'https://example.test/unchanged', title: 'Unchanged page', text: filler(10, 'unchanged'), sourceKind: 'web' });
    eq(await store.count(), before, 'count should not grow on re-save');
  });

  it('bulk ingest deduplicates and indexes title-only items', async () => {
    await freshDb();
    await useLocalProvider();
    const items = [
      { url: 'https://example.test/a', title: 'Alpha article about turbines', sourceKind: 'history', siteName: 'example.test' },
      { url: 'https://example.test/b', title: 'Beta article about turbines', sourceKind: 'history', siteName: 'example.test' },
      { url: 'https://example.test/a', title: 'Alpha article about turbines', sourceKind: 'history', siteName: 'example.test' },
    ];
    const res = await ingestMod.ingestBatch(items);
    eq(res.added, 2, 'the duplicate URL should be dropped');
    const hits = await index.searchLexical('turbines');
    eq(hits.length, 2, 'both should be lexically findable');
  });
});

// ================= migration =================

describe('Migration from v1', () => {
  it('lifts v1 embeddings into the index without any API call', async () => {
    // Build a genuine v1 database: version 1, embeddings inline on each
    // memory record, no vector/chunk/postings stores.
    store._resetConnection();
    index._reset();
    await new Promise((resolve, reject) => {
      const del = indexedDB.deleteDatabase('mem');
      del.onsuccess = resolve;
      del.onerror = () => reject(del.error);
      del.onblocked = resolve;
    });

    const v1Vec = Array.from(local.embed('legacy memory about tidal turbines and marine energy'));
    await new Promise((resolve, reject) => {
      const req = indexedDB.open('mem', 1);
      req.onupgradeneeded = (e) => {
        const db = e.target.result;
        const s = db.createObjectStore('memories', { keyPath: 'id' });
        s.createIndex('url', 'url', { unique: false });
        s.createIndex('createdAt', 'createdAt', { unique: false });
        s.createIndex('tags', 'tags', { unique: false, multiEntry: true });
      };
      req.onsuccess = () => {
        const db = req.result;
        const t = db.transaction('memories', 'readwrite');
        t.objectStore('memories').put({
          id: 'legacy1',
          url: 'https://example.test/legacy',
          title: 'Tidal turbines',
          summary: 'Legacy memory about tidal turbines and marine energy generation.',
          text: 'Tidal turbines convert marine currents into electricity using submerged rotors.',
          tags: ['tidal', 'marine energy'],
          keyFacts: [],
          embedding: v1Vec,
          createdAt: Date.now() - 86400000,
          updatedAt: Date.now() - 86400000,
          sourceKind: 'web',
        });
        t.oncomplete = () => { db.close(); resolve(); };
        t.onerror = () => reject(t.error);
      };
      req.onerror = () => reject(req.error);
    });

    const result = await store.migrateIfNeeded();
    assert(result.migrated, 'migration should have run');
    eq(result.count, 1, 'one memory should have migrated');

    const m = await store.get('legacy1');
    assert(m, 'the memory should survive migration');
    eq(m.title, 'Tidal turbines');
    assert(!('embedding' in m), 'the inline embedding should have been stripped from the record');

    const rec = await store.getChunks('legacy1');
    assert(rec?.docVec, 'the vector should now live in the chunk store');
    return `migrated ${result.count} memory, vector preserved at ${rec.docVec.length} dims`;
  });

  it('migrated memories are retrievable by both arms', async () => {
    await useLocalProvider();
    // The v1 vector carried no space tag, so it was adopted into the index.
    const lex = await index.searchLexical('tidal turbines');
    gt(lex.length, 0, 'BM25 should find the migrated memory');
    eq(lex[0].id, 'legacy1');

    const sem = await index.searchVectors(local.embed('tidal turbines marine energy'), { k: 3 });
    gt(sem.length, 0, 'the migrated vector should be searchable');
    eq(sem[0].id, 'legacy1');
    return `lexical ${lex[0].score.toFixed(3)}, semantic ${sem[0].score.toFixed(3)}`;
  });

  it('migration is idempotent', async () => {
    const again = await store.migrateIfNeeded();
    assert(!again.migrated, 're-running migration should be a no-op');
    assert(await store.get('legacy1'), 'the memory should still be there');
  });
});

// ================= episodes =================

describe('Episodes', () => {
  it('splits activity on idle gaps', async () => {
    await freshDb();
    await useLocalProvider();
    const base = Date.now() - 10 * 86400000;
    // Session one: four items a few minutes apart.
    for (let i = 0; i < 4; i++) {
      await seed({ id: `e1-${i}`, title: `Auth debugging step ${i}`, body: 'Investigating the authentication redirect loop in the login flow.', summary: 'Auth redirect investigation.', createdAt: base + i * 5 * 60000 });
    }
    // Three hours later: a second session.
    const later = base + 3 * 3600000;
    for (let i = 0; i < 4; i++) {
      await seed({ id: `e2-${i}`, title: `Pasta recipe ${i}`, body: 'Reading about slow cooked tomato sauce and fresh pasta technique.', summary: 'Cooking research.', createdAt: later + i * 5 * 60000 });
    }
    await index.flush();

    const res = await episodes.rebuildEpisodes({ gapMinutes: 45 });
    eq(res.episodes, 2, `expected two episodes, got ${res.episodes}`);
    const list = await episodes.listEpisodes();
    eq(list.length, 2);
    assert(list.every((e) => e.count === 4), 'each episode should hold four items');
    return `episodes: ${list.map((e) => `${e.title} (${e.count})`).join(' | ')}`;
  });

  it('gives each episode a usable name with no model call', async () => {
    const list = await episodes.listEpisodes();
    for (const e of list) {
      assert(e.title && e.title.length > 1, 'every episode needs a name immediately');
      assert(!e.named, 'the deterministic name should not be marked as model-written');
    }
    return list.map((e) => e.title).join(' | ');
  });

  it('writes the episode back onto its memories', async () => {
    const m = await store.get('e1-0');
    assert(m.episodeId, 'the memory should know which session it belonged to');
    const full = await episodes.episodeFor('e1-0');
    eq(full.memories.length, 4);
  });

  it('ignores future-dated records', async () => {
    await seed({ id: 'future1', title: 'Upcoming exam', body: 'An exam scheduled for next week in the main hall.', summary: 'Upcoming exam.', createdAt: Date.now() + 7 * 86400000, sourceKind: 'calendar' });
    await index.flush();
    const res = await episodes.rebuildEpisodes({ gapMinutes: 45 });
    const list = await episodes.listEpisodes();
    assert(list.every((e) => !e.memIds.includes('future1')), 'a future event is not something that happened');
    return `${res.episodes} episodes, future item excluded`;
  });
});

// ================= entities =================

describe('Entity graph', () => {
  it('normalises names and strips honorifics', () => {
    eq(entities.normName('Mr. Patel'), 'patel');
    eq(entities.normName('  Jamie   Chen '), 'jamie chen');
    eq(entities.normName('Chen, Jamie Jr.'), 'chen jamie');
  });

  it('reads a name out of an email header', () => {
    eq(entities.nameFromEmailField('"Jamie Chen" <jamie@example.com>'), 'Jamie Chen');
    eq(entities.nameFromEmailField('jamie.chen@example.com'), 'jamie chen');
  });

  it('folds an unambiguous first name into the full name', async () => {
    await freshDb();
    await entities.linkEntities('m1', [{ name: 'Jamie Chen', kind: 'person' }], Date.now());
    await entities.linkEntities('m2', [{ name: 'Jamie', kind: 'person' }], Date.now());
    const all = await store.entitiesAll();
    const people = all.filter((e) => e.kind === 'person');
    eq(people.length, 1, `expected one person, got ${people.map((p) => p.name).join(', ')}`);
    eq(people[0].count, 2, 'both memories should attach to the same person');
    assert(people[0].aliases.includes('jamie'), 'the short form should be recorded as an alias');
  });

  it('refuses to merge an ambiguous first name', async () => {
    await freshDb();
    await entities.linkEntities('m1', [{ name: 'Jamie Chen', kind: 'person' }], Date.now());
    await entities.linkEntities('m2', [{ name: 'Jamie Rivera', kind: 'person' }], Date.now());
    await entities.linkEntities('m3', [{ name: 'Jamie', kind: 'person' }], Date.now());
    const people = (await store.entitiesAll()).filter((e) => e.kind === 'person');
    eq(people.length, 3, 'a bare first name matching two people must stay separate');
    return 'ambiguous "Jamie" kept distinct from Jamie Chen and Jamie Rivera';
  });

  it('drops noise names', async () => {
    await freshDb();
    await entities.linkEntities('m1', [
      { name: 'no-reply', kind: 'person' },
      { name: '12345', kind: 'org' },
      { name: 'Real Person', kind: 'person' },
    ], Date.now());
    const all = await store.entitiesAll();
    eq(all.length, 1);
    eq(all[0].name, 'Real Person');
  });

  it('derives people from metadata with no model call', () => {
    const found = entities.implicitEntities({
      author: '"Jamie Chen" <jamie@example.com>',
      sourceKind: 'gmail',
      extra: { attendees: ['Mr. Patel <patel@example.com>'], courseName: 'Biology 11' },
    });
    const names = found.map((f) => f.name);
    assert(names.includes('Jamie Chen'), `expected Jamie Chen in ${names.join(', ')}`);
    assert(names.includes('Mr. Patel'), `expected Mr. Patel in ${names.join(', ')}`);
    assert(names.includes('Biology 11'), 'the course should become an event entity');
  });
});

// ================= open loops =================

describe('Open loops', () => {
  it('surfaces an overdue assignment that was never turned in', async () => {
    await freshDb();
    await useLocalProvider();
    const now = Date.now();
    await seed({
      id: 'hw1', title: 'Unit 3 lab report', body: 'Write up the cell respiration lab results and submit the report.',
      summary: 'Lab report on cell respiration.', sourceKind: 'classroom', createdAt: now - 10 * 86400000,
      extra: { due: now - 2 * 86400000, submitted: false, courseName: 'Biology 11' },
    });
    await seed({
      id: 'hw2', title: 'Unit 2 essay', body: 'Essay comparing two accounts of the industrial revolution.',
      summary: 'History essay.', sourceKind: 'classroom', createdAt: now - 20 * 86400000,
      extra: { due: now - 15 * 86400000, submitted: true, courseName: 'History 11' },
    });
    const loops = await openloops.findOpenLoops({ now });
    eq(loops.length, 1, `expected one loop, got ${loops.map((l) => l.kind).join(', ')}`);
    eq(loops[0].kind, 'assignment-overdue');
    assert(loops[0].reason.includes('Biology 11'), 'the reason should name the course');
    return loops[0].reason;
  });

  it('detects a long read that was abandoned partway', async () => {
    await freshDb();
    await useLocalProvider();
    const now = Date.now();
    await seed({
      id: 'read1', title: 'A very long essay', body: filler(60, 'essay'),
      summary: 'A long essay about many things.', createdAt: now - 5 * 86400000,
      extra: { dwellMs: 240000, scrollPct: 0.18 },
    });
    // Same length, but finished — must not be flagged.
    await seed({
      id: 'read2', title: 'Another long essay', body: filler(60, 'other'),
      summary: 'Another long essay.', createdAt: now - 5 * 86400000,
      extra: { dwellMs: 600000, scrollPct: 0.95 },
    });
    const loops = await openloops.findOpenLoops({ now });
    eq(loops.length, 1);
    eq(loops[0].memory.id, 'read1');
    assert(/18%/.test(loops[0].reason), `reason should quote the progress, got: ${loops[0].reason}`);
    return loops[0].reason;
  });

  it('stays silent when the engagement signals are missing', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({
      id: 'nosignal', title: 'Long page with no telemetry', body: filler(60, 'nosignal'),
      summary: 'A long page.', createdAt: Date.now() - 5 * 86400000, extra: {},
    });
    const loops = await openloops.findOpenLoops();
    eq(loops.length, 0, 'without dwell and scroll data it must not guess');
  });

  it('a dismissed loop stays dismissed', async () => {
    await freshDb();
    await useLocalProvider();
    const now = Date.now();
    await seed({
      id: 'hw3', title: 'Overdue task', body: 'A task that was never completed by the due date.',
      summary: 'Overdue task.', sourceKind: 'classroom', createdAt: now - 9 * 86400000,
      extra: { due: now - 86400000, submitted: false, courseName: 'Physics' },
    });
    const before = await openloops.findOpenLoops({ now });
    eq(before.length, 1);
    await openloops.dismiss(before[0].id);
    const after = await openloops.findOpenLoops({ now });
    eq(after.length, 0, 'the dismissed loop should not come back');
  });
});

// ================= resurface =================

describe('Resurface', () => {
  it('retention decays monotonically with age', () => {
    const s = 10;
    let prev = Infinity;
    for (const age of [1, 5, 10, 20, 40, 80]) {
      const r = resurface.retention(age, s);
      assert(r < prev, `retention should fall as age grows (${age} days)`);
      prev = r;
    }
    close(resurface.retention(10, 10), Math.exp(-1), 1e-6, 'one stability period should leave 1/e');
  });

  it('deliberate acts make a memory more durable', () => {
    const glanced = resurface.stabilityDays({ sourceKind: 'history', lightweight: true, extra: {} });
    const bookmarked = resurface.stabilityDays({ sourceKind: 'bookmark', extra: {} });
    const revisited = resurface.stabilityDays({ sourceKind: 'web', extra: { visitCount: 12 } });
    gt(bookmarked, glanced, 'a bookmark should outlast a glance');
    gt(revisited, glanced, 'repeat visits should outlast a single one');
    return `glanced ${glanced.toFixed(1)}d, bookmarked ${bookmarked.toFixed(1)}d, revisited ${revisited.toFixed(1)}d`;
  });

  it('skips things that are still fresh and things long gone', async () => {
    await freshDb();
    await useLocalProvider();
    const now = Date.now();
    const DAY = 86400000;
    await seed({ id: 'fresh', title: 'Read this morning', body: 'A document read only hours ago about ordinary matters.', summary: 'Fresh.', createdAt: now - 3600000 });
    await seed({ id: 'ancient', title: 'Read two years ago', body: 'A document read a very long time ago about ordinary matters.', summary: 'Ancient.', createdAt: now - 730 * DAY, sourceKind: 'history' });
    await seed({ id: 'slipping', title: 'Read a few weeks ago', body: 'A bookmarked document read a few weeks ago about ordinary matters.', summary: 'Slipping.', createdAt: now - 25 * DAY, sourceKind: 'bookmark' });

    const due = await resurface.dueForResurface({ now, limit: 10 });
    const ids = due.map((d) => d.memory.id);
    assert(!ids.includes('fresh'), 'something read this morning is not slipping');
    assert(ids.includes('slipping'), `the bookmarked item from 25 days ago should be due; got ${ids.join(', ')}`);
    return `due: ${ids.join(', ')}`;
  });

  it('respects the cooldown after being shown', async () => {
    const before = await resurface.dueForResurface({ limit: 10 });
    gt(before.length, 0, 'should have something to show first');
    await resurface.markResurfaced(before.map((d) => d.memory.id));
    const after = await resurface.dueForResurface({ limit: 10 });
    eq(after.length, 0, 'nothing should reappear inside the cooldown window');
  });

  it('connects semantically close memories that are far apart in time', async () => {
    await freshDb();
    await useLocalProvider();
    const now = Date.now();
    const DAY = 86400000;
    await seed({
      id: 'old-note', title: 'Spaced repetition and memory',
      body: 'Reviewing material at expanding intervals exploits the spacing effect to consolidate memory more durably than cramming does.',
      summary: 'Spaced repetition consolidates memory at expanding intervals.',
      createdAt: now - 60 * DAY,
    });
    await seed({
      id: 'new-note', title: 'Expanding interval review consolidates memory',
      body: 'The spacing effect means reviewing material at expanding intervals consolidates memory far more durably than cramming.',
      summary: 'Expanding interval review beats cramming for memory consolidation.',
      createdAt: now - 3600000,
    });
    await seed({ id: 'unrelated', title: 'Ferry timetable', body: 'Winter sailings depart hourly from the north quay on weekdays.', summary: 'Ferry timetable.', createdAt: now - 90 * DAY });
    await index.flush();

    const connections = await resurface.findConnections({ anchors: 5, limit: 5, now });
    gt(connections.length, 0, 'the two related notes should connect');
    const pair = connections[0];
    const ids = [pair.recent.id, pair.older.id].sort().join(',');
    eq(ids, 'new-note,old-note', `expected the two memory notes to pair, got ${ids}`);
    gt(pair.gapDays, 13, 'the pair should be separated by weeks');
    return `${pair.reason} (similarity ${pair.similarity.toFixed(3)})`;
  });
});

// ================= conversation =================

describe('Conversation', () => {
  it('recognises follow-ups that depend on context', () => {
    for (const q of ['why?', 'why does that happen', 'tell me more', 'what about the second one', 'and then?', 'how so']) {
      assert(isFollowUp(q), `"${q}" should be treated as a follow-up`);
    }
  });

  it('treats a self-contained question as standalone', () => {
    assert(!isFollowUp('what did I read about perovskite solar cell degradation last month'),
      'a fully specified question needs no rewriting');
  });
});

// ================= provider fallback =================

describe('Provider fallback', () => {
  it('falls through to on-device when the cloud provider has no key', async () => {
    await ai.switchProvider('gemini');
    // No Gemini key is set in this origin's storage, and the stubbed
    // on-device model reports as available.
    const effective = await ai.effectiveProvider();
    eq(effective, 'local', 'should fall back to the on-device model');
    const { space } = await ai.embedMany(['a test sentence for the fallback path']);
    eq(space, LOCAL_SPACE, 'the fallback embedding must be tagged with the local space');
    await ai.switchProvider('local');
  });

  it('reports the space that produced each embedding', async () => {
    const res = await ai.embedOne('another sentence');
    eq(res.space, LOCAL_SPACE);
    eq(res.provider, 'local');
    eq(res.vector.length, 1536);
  });
});

// ================= time scoping =================

describe('Time scoping', () => {
  // Tuesday 4 Aug 2026, 09:00 — deliberately a morning, because that is when
  // rolling-offset windows diverge most from calendar days.
  const NOW = new Date(2026, 7, 4, 9, 0, 0).getTime();
  const day = (ts) => new Date(ts).getDate();

  it('"yesterday" means the whole of yesterday, not 24-48 hours ago', () => {
    const s = search.queryTimeScope('what did I read yesterday', NOW);
    assert(s, 'should be time-anchored');
    eq(day(s.from), 3, 'should start at the beginning of Monday');
    eq(new Date(s.from).getHours(), 0, 'should start at midnight');
    eq(day(s.to), 4, 'should end at the start of Tuesday');
    // The rolling version would have started Sunday morning.
    assert(s.from >= NOW - 48 * 3600000, 'must not reach back into Sunday');
    return `${new Date(s.from).toDateString()} 00:00 → ${new Date(s.to).toDateString()} 00:00`;
  });

  it('"today" covers all of today, including the rest of it', () => {
    const s = search.queryTimeScope('what have I read today', NOW);
    eq(day(s.from), 4);
    eq(new Date(s.from).getHours(), 0);
    assert(s.to > NOW, 'should extend past the current moment');
  });

  it('"this week" starts on Monday, not seven days ago', () => {
    const s = search.queryTimeScope('what did I read this week', NOW);
    eq(new Date(s.from).getDay(), 1, 'should start on a Monday');
    eq(day(s.from), 3, 'the Monday of this week is the 3rd');
  });

  it('"last week" is the previous calendar week', () => {
    const s = search.queryTimeScope('what did I do last week', NOW);
    eq(new Date(s.from).getDay(), 1, 'starts Monday');
    eq(day(s.from), 27, 'the previous Monday is 27 July');
    eq(day(s.to), 3, 'and ends where this week begins');
  });

  it('does not hijack ordinary questions containing "now" or "just"', () => {
    // These used to trigger a hard four-hour filter, silently discarding the
    // rest of the corpus for a question that had nothing to do with time.
    for (const q of [
      'what do I know about perovskites now',
      'I just want to know about tidal turbines',
      'what did I learn earlier about encapsulation',
    ]) {
      assert(!search.queryTimeScope(q, NOW), `"${q}" should not be time-anchored`);
    }
  });

  it('still recognises genuinely recent questions', () => {
    for (const q of ['what was I just doing', 'what did I open in the last hour']) {
      assert(search.queryTimeScope(q, NOW), `"${q}" should be time-anchored`);
    }
  });
});

// ================= write ownership =================

describe('Index write ownership', () => {
  it('rejects writes when the index is read-only', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'ro1', title: 'Before read-only', body: 'A document indexed while writes were still permitted.', summary: 'Before.' });
    await index.flush();

    index.setReadOnly(true);
    try {
      let threw = false;
      try {
        await index.addDoc({ id: 'ro2', vec: null, space: null, createdAt: Date.now(), chunks: [], tokensText: 'should not be written' });
      } catch { threw = true; }
      assert(threw, 'addDoc must throw rather than corrupt the shared ordinal table');

      threw = false;
      try { await index.removeDoc('ro1'); } catch { threw = true; }
      assert(threw, 'removeDoc must throw too');

      // Reads keep working — that is the whole point of read-only.
      const hits = await index.searchLexical('read-only permitted');
      gt(hits.length, 0, 'reads must still work');
    } finally {
      index.setReadOnly(false);
    }
  });

  it('a read-only flush is a no-op rather than an error', async () => {
    index.setReadOnly(true);
    try {
      await index.flush(); // must not throw
    } finally {
      index.setReadOnly(false);
    }
  });
});

// ================= reminders =================

describe('Reminders', () => {
  const remindersMod = () => import('../lib/reminders.js');

  it('rehydrating with an overdue reminder does not deadlock', async () => {
    // Reminder mutations are serialised through one promise chain. Firing an
    // overdue reminder from inside rehydrate — which already holds that lock —
    // waits on a link that only settles when rehydrate returns. The deadlock
    // is silent and total: boot() never resolves, so the periodic alarms are
    // never installed, and because the reminder stays overdue every later
    // wake hangs the same way.
    const rem = await remindersMod();
    const now = Date.now();
    await store.metaSet('reminders', [
      { id: 'od1', what: 'Overdue thing', at: now - 3600000, createdAt: now - 7200000, firedAt: 0, sourceUrl: '', sourceTitle: '', origin: '', snippet: '' },
      { id: 'fut1', what: 'Future thing', at: now + 3600000, createdAt: now, firedAt: 0, sourceUrl: '', sourceTitle: '', origin: '', snippet: '' },
    ]);

    const res = await Promise.race([
      rem.rehydrate(),
      new Promise((r) => setTimeout(() => r({ deadlocked: true }), 5000)),
    ]);
    assert(!res.deadlocked, 'rehydrate() never resolved — the serialisation lock deadlocked');
    eq(res.fired, 1, 'the overdue reminder should have fired');

    const list = await rem.listReminders({ includeFired: true });
    assert(list.find((r) => r.id === 'od1')?.firedAt > 0, 'overdue should be marked fired');
    await store.metaSet('reminders', []);
    return `fired ${res.fired}, chain still responsive`;
  });

  it('the mutation chain still works after firing', async () => {
    const rem = await remindersMod();
    const now = Date.now();
    await store.metaSet('reminders', [
      { id: 'od2', what: 'Another overdue', at: now - 1000, createdAt: now - 2000, firedAt: 0, sourceUrl: '', sourceTitle: '', origin: '', snippet: '' },
    ]);
    await rem.rehydrate();
    const cancelled = await Promise.race([
      rem.cancelReminder('od2').then(() => true),
      new Promise((r) => setTimeout(() => r(false), 4000)),
    ]);
    assert(cancelled, 'a later mutation hung — the chain was left wedged');
    await store.metaSet('reminders', []);
  });
});

// ================= reconciliation =================

describe('Reconciliation', () => {
  it('re-indexes memories that were written but never indexed', async () => {
    // Exactly the state a service worker killed mid-scan leaves behind. It
    // matters because ingest dedupes on record existence, so a re-run would
    // skip these forever.
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'indexed', title: 'Properly indexed document', body: 'A document about tidal turbines that completed its indexing.', summary: 'Indexed.' });
    await index.flush();

    await store.put({
      id: 'orphan', url: 'https://example.test/orphan',
      title: 'Orphaned document about xenobiology',
      summary: 'Written to the store but never indexed, as a killed worker leaves it.',
      text: 'Written to the store but never indexed.',
      tags: [], keyFacts: [], contentType: 'article', sourceKind: 'web',
      siteName: 'example.test', author: '', favicon: '', excerpt: '', selection: '',
      publishedAt: '', mime: '', extra: null, createdAt: Date.now(), updatedAt: Date.now(),
    });

    eq((await index.searchLexical('xenobiology')).length, 0, 'should be unfindable before repair');
    const res = await index.reconcile();
    eq(res.orphans, 1, 'should have found exactly one orphan');
    gt((await index.searchLexical('xenobiology')).length, 0, 'should be findable after repair');
    return `${res.orphans} re-indexed, ${res.stale} stale retired`;
  });

  it('retires ordinals whose record is gone', async () => {
    await freshDb();
    await useLocalProvider();
    await seed({ id: 'keep', title: 'Surviving document', body: 'A document about marine energy that stays put.', summary: 'Survives.' });
    await seed({ id: 'vanish', title: 'Vanishing document', body: 'A document about hydrothermal vents deleted behind the index.', summary: 'Vanishes.' });
    await index.flush();

    // Delete the record without going through remove(), so the index keeps
    // its ordinal — the mirror image of an orphan.
    const db = await store.ready();
    await new Promise((resolve, reject) => {
      const t = db.transaction('memories', 'readwrite');
      t.objectStore('memories').delete('vanish');
      t.oncomplete = resolve;
      t.onerror = () => reject(t.error);
    });

    gt((await index.searchLexical('hydrothermal')).length, 0, 'still scoring before repair');
    const res = await index.reconcile();
    eq(res.stale, 1, 'should have retired one stale ordinal');
    eq((await index.searchLexical('hydrothermal')).length, 0, 'a deleted memory must stop scoring');
    gt((await index.searchLexical('marine energy')).length, 0, 'the survivor is untouched');
  });

  it('is a no-op when the index and store already agree', async () => {
    const res = await index.reconcile();
    eq(res.orphans, 0);
    eq(res.stale, 0);
  });
});

// ================= tokenizer =================

describe('Tokenizer', () => {
  it('keeps Latin and digit runs inside mixed CJK text', () => {
    // Splitting CJK out while discarding the rest threw away exactly the most
    // searchable tokens — product names, years, model numbers.
    const t = text.tokenize('Windows11の設定');
    assert(t.includes('windows11'), `expected windows11 in ${JSON.stringify(t)}`);
    assert(t.includes('設'), 'CJK characters should each be a token');
    return JSON.stringify(t);
  });

  it('indexes non-Latin scripts at all', () => {
    for (const [s, expected] of [
      ['Привет мир', 'привет'],
      ['Γειά σου κόσμε', 'γειά'],
      ['café résumé', 'café'],
    ]) {
      const t = text.tokenize(s);
      assert(t.includes(expected), `expected ${expected} in ${JSON.stringify(t)}`);
    }
  });

  it('does not truncate accented words', () => {
    // The ASCII-only pattern turned "café" into "caf".
    assert(!text.tokenize('café').includes('caf'), 'must not split at the accent');
  });

  it('keeps hyphenated terms whole', () => {
    assert(text.tokenize('state-of-the-art').includes('state-of-the-art'));
  });

  it('declares an analyzer version so a change forces a reindex', () => {
    gt(text.ANALYZER_VERSION, 1, 'version should be past the ASCII-only original');
  });
});

// ================= commitment detection =================

describe('Commitment detection', () => {
  // A fixed Wednesday so weekday arithmetic is deterministic.
  const NOW = new Date(2026, 2, 4, 10, 0, 0).getTime(); // Wed 4 Mar 2026, 10:00

  const detect = (t) => commitments.detectCommitment(t, { now: NOW });

  it('resolves a weekday and clock time together', () => {
    const w = commitments.parseWhen("the lab report is due Friday at 3pm", NOW);
    assert(w, 'should parse');
    const d = new Date(w.at);
    eq(d.getDay(), 5, 'should land on Friday');
    eq(d.getHours(), 15, 'should be 3pm');
    eq(d.getDate(), 6, 'should be the coming Friday, 6 March');
  });

  it('a bare weekday means the next one, never today', () => {
    const w = commitments.parseWhen('practice on wednesday', NOW); // NOW is a Wednesday
    const d = new Date(w.at);
    eq(d.getDay(), 3);
    eq(d.getDate(), 11, 'should roll forward a week rather than meaning today');
  });

  it('handles relative offsets', () => {
    eq(commitments.parseWhen('in 30 minutes', NOW).at, NOW + 30 * 60000);
    eq(commitments.parseWhen('in 2 hours', NOW).at, NOW + 2 * 3600000);
    eq(commitments.parseWhen('in 3 days', NOW).at, NOW + 3 * 86400000);
  });

  it('handles tomorrow, tonight, and named dates', () => {
    eq(new Date(commitments.parseWhen('tomorrow at 9am', NOW).at).getDate(), 5);
    eq(new Date(commitments.parseWhen('tonight', NOW).at).getHours(), 20);
    const march = commitments.parseWhen('March 20th', NOW);
    eq(new Date(march.at).getMonth(), 2);
    eq(new Date(march.at).getDate(), 20);
  });

  it('keeps a passed same-day time in the past rather than inventing tomorrow', () => {
    // NOW is 10:00, so "today at 8am" has already gone. "Today" has to keep
    // meaning today, so detection can recognise it as past and stay quiet.
    const w = commitments.parseWhen('today at 8am', NOW);
    eq(new Date(w.at).getDate(), 4, 'should stay on today');
    assert(w.at < NOW, 'should resolve to a past timestamp');
  });

  it('rolls a bare clock time forward to its next occurrence', () => {
    // With no day attached, "at 8" said at 10:00 means the coming 8.
    const w = commitments.parseWhen('call me at 8', NOW);
    assert(w.at > NOW, 'a bare time should resolve into the future');
  });

  it('catches a real chat message with an abbreviation and no cue word', () => {
    // The message that exposed both gaps: "tmrw" wasn't recognised as
    // tomorrow, and neither "hackathon" nor "ending" was a cue, so a genuine
    // deadline produced silence.
    const c = detect('yo i have another hackathon ending tmrw at 12pm im so fried');
    assert(c, 'should detect');
    eq(new Date(c.at).getDate(), 5, 'tmrw should resolve to tomorrow');
    eq(new Date(c.at).getHours(), 12, 'should be 12pm');
    return `"${c.what}" → ${c.whenText} (confidence ${c.confidence.toFixed(2)})`;
  });

  it('understands the abbreviations people actually type', () => {
    for (const [line, dayOfMonth] of [
      ['flight is tmr at 7am', 5],
      ['assignment due tmrw', 5],
      ['see you 2nite', 4],
      ['party tonite at 9pm', 4],
    ]) {
      const w = commitments.parseWhen(line, NOW);
      assert(w, `"${line}" should parse`);
      eq(new Date(w.at).getDate(), dayOfMonth, `"${line}" resolved to the wrong day`);
    }
  });

  it('treats naming a day as evidence in its own right', () => {
    // Requiring a cue word as well meant real messages went unnoticed; no cue
    // list can cover what people actually do with their time.
    const c = detect('the thing is on saturday at 4pm');
    assert(c, 'a named day and time should be enough on its own');
    // But a bare clock with no day still needs a cue, or every mention of a
    // time in conversation would fire.
    assert(!detect('I watched the 3pm showing and it was great'), 'a bare clock still needs a cue');
  });

  it('handles end-of-day and end-of-week deadlines', () => {
    const eod = commitments.parseWhen('essay due eod', NOW);
    eq(new Date(eod.at).getDate(), 4, 'eod is today');
    eq(new Date(eod.at).getHours(), 17, 'eod should mean late afternoon, not midnight');
    const eow = commitments.parseWhen('report due eow', NOW);
    eq(new Date(eow.at).getDay(), 5, 'eow should land on Friday');
  });

  it('fires on a clear obligation with a time', () => {
    const c = detect("don't forget the bio lab report is due Friday at 3pm");
    assert(c, 'should detect a commitment');
    eq(new Date(c.at).getDay(), 5);
    gt(c.confidence, 0.7, 'a deadline with an explicit time should score high');
    return `"${c.what}" → ${c.whenText} (confidence ${c.confidence.toFixed(2)})`;
  });

  it('fires on a rescheduled meeting', () => {
    const c = detect('heads up, the standup moved to tomorrow at 2pm');
    assert(c, 'should detect');
    eq(new Date(c.at).getHours(), 14);
    return `"${c.what}" → ${c.whenText}`;
  });

  it('fires on a direct request with a deadline', () => {
    const c = detect('can you send me the slides by Thursday?');
    assert(c, 'should detect a request with a deadline');
    eq(new Date(c.at).getDay(), 4);
    return `"${c.what}" → ${c.whenText} (confidence ${c.confidence.toFixed(2)})`;
  });

  it('stays silent on a time with no obligation', () => {
    assert(!detect('I watched the 3pm showing and it was great'), 'no obligation cue');
    assert(!detect('the train gets in around 6 usually'), 'no obligation cue');
  });

  it('stays silent on an obligation with no time', () => {
    assert(!detect("don't forget to bring your notes"), 'no time reference');
    assert(!detect('the deadline was last week and we missed it'), 'no parseable future time');
  });

  it('stays silent on hedged plans', () => {
    assert(!detect('maybe we could meet friday?'), 'hedged and questioned');
    assert(!detect('I might go to the game on saturday'), 'hedged');
  });

  it('stays silent on ordinary chatter', () => {
    for (const line of [
      'lol ok', 'the score was 3-2 at halftime', 'https://example.com/meeting-at-3pm',
      'sounds good to me', 'brb', 'that was so funny',
    ]) {
      assert(!detect(line), `should not fire on: ${line}`);
    }
  });

  it('ignores anything already in the past', () => {
    assert(!commitments.detectCommitment('the meeting was at 9am today', { now: NOW }),
      'a passed time is a fact, not a commitment');
  });

  it('strips a chat name prefix from the label', () => {
    const c = detect('Jamie Chen: remember to submit the permission form by Friday');
    assert(c, 'should detect');
    assert(!c.what.startsWith('Jamie Chen:'), `label should drop the speaker prefix, got: ${c.what}`);
    return `label: "${c.what}"`;
  });

  it('describes the countdown in plain language', () => {
    eq(commitments.describeWhen(NOW + 25 * 60000, NOW), 'in 25 min');
    eq(commitments.describeWhen(NOW + 3 * 3600000, NOW), 'in 3 hours');
    eq(commitments.describeWhen(NOW + 26 * 3600000, NOW), 'tomorrow');
    eq(commitments.describeWhen(NOW + 3 * 86400000, NOW), 'in 3 days');
  });

  it('does not fire twice on the same line', () => {
    // Idempotence matters because the observer re-reads the DOM constantly.
    const a = detect('reminder: rehearsal is at 6pm tomorrow');
    const b = detect('reminder: rehearsal is at 6pm tomorrow');
    eq(a.at, b.at, 'the same text must always produce the same timestamp');
    eq(a.what, b.what);
  });
});

// ---------- runner ----------

const resultsEl = document.getElementById('results');
const totalsEl = document.getElementById('totals');
const logEl = document.getElementById('log');
const runBtn = document.getElementById('run');

async function run() {
  runBtn.disabled = true;
  resultsEl.innerHTML = '';
  totalsEl.textContent = '';
  const summary = { pass: 0, fail: 0, skip: 0 };
  const report = [];

  for (const suite of suites) {
    const section = document.createElement('section');
    const h = document.createElement('h2');
    h.textContent = suite.name;
    const count = document.createElement('span');
    count.className = 'count';
    h.appendChild(count);
    section.appendChild(h);
    resultsEl.appendChild(section);

    let localPass = 0;
    for (const c of suite.cases) {
      logEl.textContent = `${suite.name} → ${c.name}`;
      const row = document.createElement('div');
      row.className = 'case';
      const t0 = performance.now();
      let status = 'pass';
      let message = '';
      let detail = '';
      try {
        const out = await c.fn();
        if (typeof out === 'string') detail = out;
        localPass++;
        summary.pass++;
      } catch (e) {
        if (e instanceof Skip) { status = 'skip'; message = e.message; summary.skip++; }
        else { status = 'fail'; message = e.message; summary.fail++; }
      }
      const ms = Math.round(performance.now() - t0);
      row.className = `case ${status}`;
      row.innerHTML = `
        <span class="mark">${status === 'pass' ? '✓' : status === 'fail' ? '✕' : '–'}</span>
        <span class="name"></span>
        <span class="ms">${ms}ms</span>`;
      const nameEl = row.querySelector('.name');
      nameEl.textContent = c.name;
      if (message) {
        const m = document.createElement('div');
        m.className = 'msg';
        m.textContent = message;
        nameEl.appendChild(m);
      }
      if (detail) {
        const d = document.createElement('div');
        d.className = 'detail';
        d.textContent = detail;
        nameEl.appendChild(d);
      }
      section.appendChild(row);
      report.push({ suite: suite.name, name: c.name, status, message, detail, ms });
      // Yield so the page paints between cases.
      await new Promise((r) => setTimeout(r, 0));
    }
    count.textContent = `${localPass}/${suite.cases.length}`;
  }

  logEl.textContent = '';
  totalsEl.innerHTML = `<b>${summary.pass}</b> passed · <b>${summary.fail}</b> failed${summary.skip ? ` · <b>${summary.skip}</b> skipped` : ''}`;
  window.__RESULTS__ = { summary, report };
  window.__DONE__ = true;
  runBtn.disabled = false;
  return summary;
}

runBtn.addEventListener('click', run);
// Auto-run so an automated check just has to load the page and wait.
run();
